function pchgpmpsls(varargin)
% pchgpmpsls( [...] );
% MPS Ld Status
h = ne_dstat({
  'MPSLd_SS', 'MPSLd_Status', 1; ...
	'MPSLd_STBY', 'MPSLd_Status', 6; ...
	'MPSLd_PWR', 'MPSLd_Status', 7; ...
	'MPSLd_CV', 'MPSLd_Status', 8; ...
	'MPSLd_CC', 'MPSLd_Status', 10; ...
	'MPSLd_Output', 'MPSLd_Status', 13; ...
	'MPSLd_Setpt', 'MPSLd_Status', 14 }, 'Status', varargin{:} );
