function pchgpbka(varargin);
% pchgpbka( [...] );
% B Kd Amps
h = timeplot({'BKd_I_set','BKd_I_disp'}, ...
      'B Kd Amps', ...
      'Amps', ...
      {'BKd\_I\_set','BKd\_I\_disp'}, ...
      varargin{:} );
