function pchgpmpslstale(varargin);
% pchgpmpslstale( [...] );
% MPS Ld Stale
h = timeplot({'MPSLd_Stale'}, ...
      'MPS Ld Stale', ...
      'Stale', ...
      {'MPSLd\_Stale'}, ...
      varargin{:} );
