function pchgpmpsla(varargin);
% pchgpmpsla( [...] );
% MPS Ld Amps
h = timeplot({'MPSLd_I_set','MPSLd_I_disp'}, ...
      'MPS Ld Amps', ...
      'Amps', ...
      {'MPSLd\_I\_set','MPSLd\_I\_disp'}, ...
      varargin{:} );
