function picmticmgg(varargin);
% picmticmgg( [...] );
% ICM Gain Gain
h = timeplot({'ICM_Gp','ICM_Gi'}, ...
      'ICM Gain Gain', ...
      'Gain', ...
      {'ICM\_Gp','ICM\_Gi'}, ...
      varargin{:} );
