function picmticmpa(varargin);
% picmticmpa( [...] );
% ICM Peaks Amp
h = timeplot({'ICM_peak_amp_0_0','ICM_peak_amp_0_1','ICM_peak_amp_0_2'}, ...
      'ICM Peaks Amp', ...
      'Amp', ...
      {'ICM\_peak\_amp\_0\_0','ICM\_peak\_amp\_0\_1','ICM\_peak\_amp\_0\_2'}, ...
      varargin{:} );
