function picmicmhkstale(varargin);
% picmicmhkstale( [...] );
% ICM HK Stale
h = timeplot({'ICM_stale'}, ...
      'ICM HK Stale', ...
      'Stale', ...
      {'ICM\_stale'}, ...
      varargin{:} );
