function picmticmhkremainder(varargin);
% picmticmhkremainder( [...] );
% ICM HK Remainder
h = timeplot({'ICM_rem0','ICM_rem1'}, ...
      'ICM HK Remainder', ...
      'Remainder', ...
      {'ICM\_rem0','ICM\_rem1'}, ...
      varargin{:} );
