function picmticmpf(varargin);
% picmticmpf( [...] );
% ICM Peaks Freq
h = timeplot({'ICM_peak_f_0_0','ICM_peak_f_0_1','ICM_peak_f_0_2'}, ...
      'ICM Peaks Freq', ...
      'Freq', ...
      {'ICM\_peak\_f\_0\_0','ICM\_peak\_f\_0\_1','ICM\_peak\_f\_0\_2'}, ...
      varargin{:} );
