function picmticmhkremainder(varargin);
% picmticmhkremainder( [...] );
% ICM HK Remainder
h = timeplot({'ICM_rem'}, ...
      'ICM HK Remainder', ...
      'Remainder', ...
      {'ICM\_rem'}, ...
      varargin{:} );
