function pasbmhalsahkstd_def(varargin);
% pasbmhalsahkstd_def( [...] );
% HALSA HK std def
h = timeplot({'HALSA_std_def'}, ...
      'HALSA HK std def', ...
      'std def', ...
      {'HALSA\_std\_def'}, ...
      varargin{:} );
