function pasbmgnssattitude(varargin);
% pasbmgnssattitude( [...] );
% GNSS Attitude
h = timeplot({'roll','pitch'}, ...
      'GNSS Attitude', ...
      'Attitude', ...
      {'roll','pitch'}, ...
      varargin{:} );
