function pasbmpmclt(varargin);
% pasbmpmclt( [...] );
% PMC Left Temp
h = timeplot({'uDport_T1','uDport_T2'}, ...
      'PMC Left Temp', ...
      'Temp', ...
      {'uDport\_T1','uDport\_T2'}, ...
      varargin{:} );
