function pasbmdacsr(varargin);
% pasbmdacsr( [...] );
% uDACS Rate
h = timeplot({'uDport_rate','uDstbd_rate'}, ...
      'uDACS Rate', ...
      'Rate', ...
      {'uDport\_rate','uDstbd\_rate'}, ...
      varargin{:} );
