function pasbmpmclss(varargin);
% pasbmpmclss( [...] );
% PMC Left S Status 0
h = ne_dstat({
  'Left_Bridge_En', 'PMC_Left_Status0', 0; ...
	'Left_DynBrk_En', 'PMC_Left_Status0', 1; ...
	'Left_Stop_En', 'PMC_Left_Status0', 2; ...
	'Left_PosStop_En', 'PMC_Left_Status0', 3; ...
	'Left_NegStop_En', 'PMC_Left_Status0', 4; ...
	'Left_PosTrqInh_In', 'PMC_Left_Status0', 5; ...
	'Left_NegTrqInh_En', 'PMC_Left_Status0', 6; ...
	'Left_ExtBrk_En', 'PMC_Left_Status0', 7 }, 'Status 0', varargin{:} );
