function pasbmpmcrp(varargin);
% pasbmpmcrp( [...] );
% PMC Right Position
h = timeplot({'PMC_Right_Pos_SP','PMC_Right_Pos_Demand','PMC_Right_Pos_Target','PMC_Right_Pos_Measured'}, ...
      'PMC Right Position', ...
      'Position', ...
      {'PMC\_Right\_Pos\_SP','PMC\_Right\_Pos\_Demand','PMC\_Right\_Pos\_Target','PMC\_Right\_Pos\_Measured'}, ...
      varargin{:} );
