function pasbmntiming(varargin);
% pasbmntiming( [...] );
% Nav Timing
h = timeplot({'Nav_T_acc','Nav_T_rot'}, ...
      'Nav Timing', ...
      'Timing', ...
      {'Nav\_T\_acc','Nav\_T\_rot'}, ...
      varargin{:} );
