function pasbmdacst(varargin);
% pasbmdacst( [...] );
% uDACS Temp
h = timeplot({'uDport_T1','uDport_T2','uDstbd_T1','uDstbd_T2'}, ...
      'uDACS Temp', ...
      'Temp', ...
      {'uDport\_T1','uDport\_T2','uDstbd\_T1','uDstbd\_T2'}, ...
      varargin{:} );
