function pasbmpmclsstatus4(varargin);
% pasbmpmclsstatus4( [...] );
% PMC Left S Status 4
h = ne_dstat({
  'Left_ZeroVel', 'PMC_Left_Status4', 0; ...
	'Left_AtCommand', 'PMC_Left_Status4', 1; ...
	'Left_VelFollErr', 'PMC_Left_Status4', 2; ...
	'Left_PosTargVelLim', 'PMC_Left_Status4', 3; ...
	'Left_NegTargVelLim', 'PMC_Left_Status4', 4; ...
	'Left_CmdLimiterAct', 'PMC_Left_Status4', 5; ...
	'Left_InHomPos', 'PMC_Left_Status4', 6; ...
	'Left_PosFollErr', 'PMC_Left_Status4', 7; ...
	'Left_MaxTargPosLim', 'PMC_Left_Status4', 8; ...
	'Left_MinTargPosLim', 'PMC_Left_Status4', 9; ...
	'Left_SetPosActive', 'PMC_Left_Status4', 10; ...
	'Left_HomingActive', 'PMC_Left_Status4', 12; ...
	'Left_SafeTrqOff', 'PMC_Left_Status4', 13; ...
	'Left_HomingDone', 'PMC_Left_Status4', 14; ...
	'Left_ZeroPos', 'PMC_Left_Status4', 15 }, 'Status 4', varargin{:} );
