function pasbbmbbmbt(varargin);
% pasbbmbbmbt( [...] );
% B3MB Temps
h = timeplot({'B3MB_T_mean','B3MB_T_min','B3MB_T_max'}, ...
      'B3MB Temps', ...
      'Temps', ...
      {'B3MB\_T\_mean','B3MB\_T\_min','B3MB\_T\_max'}, ...
      varargin{:} );
