function pasbmgnssll(varargin);
% pasbmgnssll( [...] );
% GNSS Lat Lon
h = timeplot({'latitude','longitude'}, ...
      'GNSS Lat Lon', ...
      'Lat Lon', ...
      {'latitude','longitude'}, ...
      varargin{:} );
