function pasbmpmcrsstatus4(varargin);
% pasbmpmcrsstatus4( [...] );
% PMC Right S Status 4
h = ne_dstat({
  'Right_ZeroVel', 'PMC_Right_Status4', 0; ...
	'Right_AtCommand', 'PMC_Right_Status4', 1; ...
	'Right_VelFollErr', 'PMC_Right_Status4', 2; ...
	'Right_PosTargVelLim', 'PMC_Right_Status4', 3; ...
	'Right_NegTargVelLim', 'PMC_Right_Status4', 4; ...
	'Right_CmdLimiterAct', 'PMC_Right_Status4', 5; ...
	'Right_InHomPos', 'PMC_Right_Status4', 6; ...
	'Right_PosFollErr', 'PMC_Right_Status4', 7; ...
	'Right_MaxTargPosLim', 'PMC_Right_Status4', 8; ...
	'Right_MinTargPosLim', 'PMC_Right_Status4', 9; ...
	'Right_SetPosActive', 'PMC_Right_Status4', 10; ...
	'Right_HomingActive', 'PMC_Right_Status4', 12; ...
	'Right_SafeTrqOff', 'PMC_Right_Status4', 13; ...
	'Right_HomingDone', 'PMC_Right_Status4', 14; ...
	'Right_ZeroPos', 'PMC_Right_Status4', 15 }, 'Status 4', varargin{:} );
