function pasbmgnsshks(varargin);
% pasbmgnsshks( [...] );
% GNSS HK System
h = timeplot({'system_status'}, ...
      'GNSS HK System', ...
      'System', ...
      {'system\_status'}, ...
      varargin{:} );
