function pasbmpmcrsstatus2(varargin);
% pasbmpmcrsstatus2( [...] );
% PMC Right S Status 2
h = ne_dstat({
  'Right_ParRestoreErr', 'PMC_Right_Status2', 0; ...
	'Right_ParStoreErr', 'PMC_Right_Status2', 1; ...
	'Right_InvHallState', 'PMC_Right_Status2', 2; ...
	'Right_PhaseSyncErr', 'PMC_Right_Status2', 3; ...
	'Right_MotorOverT', 'PMC_Right_Status2', 4; ...
	'Right_PhaseDetFault', 'PMC_Right_Status2', 5; ...
	'Right_FBSensorErr', 'PMC_Right_Status2', 6; ...
	'Right_MotorOverSpeed', 'PMC_Right_Status2', 7; ...
	'Right_MaxMeasuredPos', 'PMC_Right_Status2', 8; ...
	'Right_MinMeasuredPos', 'PMC_Right_Status2', 9; ...
	'Right_CommError', 'PMC_Right_Status2', 10; ...
	'Right_PWMBrokenWire', 'PMC_Right_Status2', 11; ...
	'Right_MotionEngErr', 'PMC_Right_Status2', 12; ...
	'Right_MotionEngAbrt', 'PMC_Right_Status2', 13 }, 'Status 2', varargin{:} );
