function pasbmpmclc(varargin);
% pasbmpmclc( [...] );
% PMC Left Current
h = timeplot({'PMC_Left_I_Demand','PMC_Left_I_Measured'}, ...
      'PMC Left Current', ...
      'Current', ...
      {'PMC\_Left\_I\_Demand','PMC\_Left\_I\_Measured'}, ...
      varargin{:} );
