function pasbmgnsshkstale(varargin);
% pasbmgnsshkstale( [...] );
% GNSS HK Stale
h = timeplot({'SD_stale','SD_n_reports','SD_nc'}, ...
      'GNSS HK Stale', ...
      'Stale', ...
      {'SD\_stale','SD\_n\_reports','SD\_nc'}, ...
      varargin{:} );
