function pasbmpmcrsstatus3(varargin);
% pasbmpmcrsstatus3( [...] );
% PMC Right S Status 3
h = ne_dstat({
  'Right_LogEntryMissed', 'PMC_Right_Status3', 0; ...
	'Right_SWDisable', 'PMC_Right_Status3', 1; ...
	'Right_UserDisable', 'PMC_Right_Status3', 2; ...
	'Right_UserPosInh', 'PMC_Right_Status3', 3; ...
	'Right_UserNegInh', 'PMC_Right_Status3', 4; ...
	'Right_CurLimiting', 'PMC_Right_Status3', 5; ...
	'Right_ContCurFoldback', 'PMC_Right_Status3', 6; ...
	'Right_CurLoopSat', 'PMC_Right_Status3', 7; ...
	'Right_UserUnderV', 'PMC_Right_Status3', 8; ...
	'Right_UserOverV', 'PMC_Right_Status3', 9; ...
	'Right_NonSinComm', 'PMC_Right_Status3', 10; ...
	'Right_PhaseDetectActive', 'PMC_Right_Status3', 11; ...
	'Right_MotionEngActive', 'PMC_Right_Status3', 12; ...
	'Right_UserAuxDisable', 'PMC_Right_Status3', 13; ...
	'Right_ShuntRegActive', 'PMC_Right_Status3', 14; ...
	'Right_PhaseDetectDone', 'PMC_Right_Status3', 15 }, 'Status 3', varargin{:} );
