function pasbmhalsahke(varargin);
% pasbmhalsahke( [...] );
% HALSA HK Elapsed
h = timeplot({'HALSA_elapsed'}, ...
      'HALSA HK Elapsed', ...
      'Elapsed', ...
      {'HALSA\_elapsed'}, ...
      varargin{:} );
