function pasbmpmcs(varargin);
% pasbmpmcs( [...] );
% PMC Stale
h = timeplot({'PMC_Stale','PMC_StaleF'}, ...
      'PMC Stale', ...
      'Stale', ...
      {'PMC\_Stale','PMC\_StaleF'}, ...
      varargin{:} );
