function pasbmhalsad(varargin);
% pasbmhalsad( [...] );
% HALSA Def
h = timeplot({'HALSA_deflection'}, ...
      'HALSA Def', ...
      'Def', ...
      {'HALSA\_deflection'}, ...
      varargin{:} );
