function pasbmgnssv(varargin);
% pasbmgnssv( [...] );
% GNSS Velocity
h = timeplot({'velocity_north','velocity_east','velocity_forward','velocity_down'}, ...
      'GNSS Velocity', ...
      'Velocity', ...
      {'velocity\_north','velocity\_east','velocity\_forward','velocity\_down'}, ...
      varargin{:} );
