function pasbmdacsmg(varargin);
% pasbmdacsmg( [...] );
% uDACS Max G
h = timeplot({'uDstbd_max_g'}, ...
      'uDACS Max G', ...
      'Max G', ...
      {'uDstbd\_max\_g'}, ...
      varargin{:} );
