function pasbmndthrust(varargin);
% pasbmndthrust( [...] );
% Nav d Thrust
h = timeplot({'Nav_dThrust_pct'}, ...
      'Nav d Thrust', ...
      'd Thrust', ...
      {'Nav\_dThrust\_pct'}, ...
      varargin{:} );
