function pasbmhalsahks(varargin);
% pasbmhalsahks( [...] );
% HALSA HK Stale
h = timeplot({'HALSA_dev_stale','HALSA_drv_stale'}, ...
      'HALSA HK Stale', ...
      'Stale', ...
      {'HALSA\_dev\_stale','HALSA\_drv\_stale'}, ...
      varargin{:} );
