function pasbmhalsahkn(varargin);
% pasbmhalsahkn( [...] );
% HALSA HK N
h = timeplot({'HALSA_n_detected'}, ...
      'HALSA HK N', ...
      'N', ...
      {'HALSA\_n\_detected'}, ...
      varargin{:} );
