function pasbmhalsahkd(varargin);
% pasbmhalsahkd( [...] );
% HALSA HK Drift
h = timeplot({'HALSA_drift'}, ...
      'HALSA HK Drift', ...
      'Drift', ...
      {'HALSA\_drift'}, ...
      varargin{:} );
