function pasbmpmclsstatus6(varargin);
% pasbmpmclsstatus6( [...] );
% PMC Left S Status 6
h = ne_dstat({
  'Left_AbsPosValid', 'PMC_Left_Status6', 0; ...
	'Left_PosStopActive', 'PMC_Left_Status6', 1; ...
	'Left_NegStopActive', 'PMC_Left_Status6', 2; ...
	'Left_ConfigSelect', 'PMC_Left_Status6', 4; ...
	'Left_BrakeCommand', 'PMC_Left_Status6', 5; ...
	'Left_DigOut1', 'PMC_Left_Status6', 6; ...
	'Left_DigOut2', 'PMC_Left_Status6', 7 }, 'Status 6', varargin{:} );
