function pasbmpmcrsstatus5(varargin);
% pasbmpmcrsstatus5( [...] );
% PMC Right S Status 5
h = ne_dstat({
  'Right_CmddStop', 'PMC_Right_Status5', 6; ...
	'Right_UserStop', 'PMC_Right_Status5', 7; ...
	'Right_Cap1Active', 'PMC_Right_Status5', 8; ...
	'Right_Cap2Active', 'PMC_Right_Status5', 9; ...
	'Right_Cap3Active', 'PMC_Right_Status5', 10; ...
	'Right_CmddPosLim', 'PMC_Right_Status5', 11; ...
	'Right_CmddNegLim', 'PMC_Right_Status5', 12 }, 'Status 5', varargin{:} );
