function pasbmdacshkm(varargin);
% pasbmdacshkm( [...] );
% uDACS HK Mode
h = timeplot({'uDport_mode','uDstbd_mode'}, ...
      'uDACS HK Mode', ...
      'Mode', ...
      {'uDport\_mode','uDstbd\_mode'}, ...
      varargin{:} );
