function pasbmhalsat(varargin);
% pasbmhalsat( [...] );
% HALSA Temp
h = timeplot({'HALSA_temperature'}, ...
      'HALSA Temp', ...
      'Temp', ...
      {'HALSA\_temperature'}, ...
      varargin{:} );
