function pasbmdacshka(varargin);
% pasbmdacshka( [...] );
% uDACS HK Axes g
h = timeplot({'uDport_x_g','uDport_y_g','uDport_z_g','uDstbd_x_g','uDstbd_y_g','uDstbd_z_g'}, ...
      'uDACS HK Axes g', ...
      'Axes g', ...
      {'uDport\_x\_g','uDport\_y\_g','uDport\_z\_g','uDstbd\_x\_g','uDstbd\_y\_g','uDstbd\_z\_g'}, ...
      varargin{:} );
