function pscopexpmcrsstatus1(varargin);
% pscopexpmcrsstatus1( [...] );
% PMC Right S Status 1
h = ne_dstat({
  'DrvReset', 'PMC_Right_Status1', 0; ...
	'DrvIntErr', 'PMC_Right_Status1', 1; ...
	'ShortCir', 'PMC_Right_Status1', 2; ...
	'CurOverShoot', 'PMC_Right_Status1', 3; ...
	'DrvUnderV', 'PMC_Right_Status1', 4; ...
	'DrvOverV', 'PMC_Right_Status1', 5; ...
	'DrvOverT', 'PMC_Right_Status1', 6 }, 'Status 1', varargin{:} );
