function pscopexmgnssh(varargin);
% pscopexmgnssh( [...] );
% GNSS Heading
h = timeplot({'Track','heading'}, ...
      'GNSS Heading', ...
      'Heading', ...
      {'Track','heading'}, ...
      varargin{:} );
