function pscopexmgnsshkstd(varargin);
% pscopexmgnsshkstd( [...] );
% GNSS HK Std
h = timeplot({'latitude_std','longitude_std','height_std'}, ...
      'GNSS HK Std', ...
      'Std', ...
      {'latitude\_std','longitude\_std','height\_std'}, ...
      varargin{:} );
