function pscopexmpmcrsstatus6(varargin);
% pscopexmpmcrsstatus6( [...] );
% PMC Right S Status 6
h = ne_dstat({
  'AbsPosValid', 'PMC_Right_Status6', 0; ...
	'PosStopActive', 'PMC_Right_Status6', 1; ...
	'NegStopActive', 'PMC_Right_Status6', 2; ...
	'ConfigSelect', 'PMC_Right_Status6', 4; ...
	'BrakeCommand', 'PMC_Right_Status6', 5; ...
	'DigOut1', 'PMC_Right_Status6', 6; ...
	'DigOut2', 'PMC_Right_Status6', 7 }, 'Status 6', varargin{:} );
