function pscopexmnt(varargin);
% pscopexmnt( [...] );
% Nav Thrust
h = timeplot({'Nav_Thrust_pct'}, ...
      'Nav Thrust', ...
      'Thrust', ...
      {'Nav\_Thrust\_pct'}, ...
      varargin{:} );
