function pscopexmgnssp(varargin);
% pscopexmgnssp( [...] );
% GNSS Position
h = timeplot({'latitude','longitude','height'}, ...
      'GNSS Position', ...
      'Position', ...
      {'latitude','longitude','height'}, ...
      varargin{:} );
