function pscopexmgnsshkf(varargin);
% pscopexmgnsshkf( [...] );
% GNSS HK Filters
h = ne_dstat({
  'orient_init', 'filter_status', 0; ...
	'nav_init', 'filter_status', 1; ...
	'heading_init', 'filter_status', 2; ...
	'UTC_init', 'filter_status', 3; ...
	'Int_GNSS_en', 'filter_status', 9; ...
	'dual_heading_active', 'filter_status', 10; ...
	'atm_alt_en', 'filter_status', 12 }, 'Filters', varargin{:} );
