function pscopexgnssp(varargin);
% pscopexgnssp( [...] );
% GNSS Position
h = timeplot({'latitude','longitude','height'}, ...
      'GNSS Position', ...
      'Position', ...
      {'latitude','longitude','height'}, ...
      varargin{:} );
