function pscopexgnssv(varargin);
% pscopexgnssv( [...] );
% GNSS Velocity
h = timeplot({'velocity_north','velocity_east','velocity_down'}, ...
      'GNSS Velocity', ...
      'Velocity', ...
      {'velocity\_north','velocity\_east','velocity\_down'}, ...
      varargin{:} );
