function pscopexpmclp(varargin);
% pscopexpmclp( [...] );
% PMC Left Position
h = timeplot({'PMC_Left_Pos_SP','PMC_Left_Pos_Demand','PMC_Left_Pos_Target','PMC_Left_Pos_Measured'}, ...
      'PMC Left Position', ...
      'Position', ...
      {'PMC\_Left\_Pos\_SP','PMC\_Left\_Pos\_Demand','PMC\_Left\_Pos\_Target','PMC\_Left\_Pos\_Measured'}, ...
      varargin{:} );
