function pscopexgnsss(varargin);
% pscopexgnsss( [...] );
% GNSS System
h = timeplot({'system_status'}, ...
      'GNSS System', ...
      'System', ...
      {'system\_status'}, ...
      varargin{:} );
