function pscopexmpmcrss(varargin);
% pscopexmpmcrss( [...] );
% PMC Right S Status 0
h = ne_dstat({
  'Right_Bridge_En', 'PMC_Right_Status0', 0; ...
	'Right_DynBrk_En', 'PMC_Right_Status0', 1; ...
	'Right_Stop_En', 'PMC_Right_Status0', 2; ...
	'Right_PosStop_En', 'PMC_Right_Status0', 3; ...
	'Right_NegStop_En', 'PMC_Right_Status0', 4; ...
	'Right_PosTrqInh_In', 'PMC_Right_Status0', 5; ...
	'Right_NegTrqInh_En', 'PMC_Right_Status0', 6; ...
	'Right_ExtBrk_En', 'PMC_Right_Status0', 7 }, 'Status 0', varargin{:} );
