function pscopexgnssstd(varargin);
% pscopexgnssstd( [...] );
% GNSS Std
h = timeplot({'latitude_std','longitude_std','height_std'}, ...
      'GNSS Std', ...
      'Std', ...
      {'latitude\_std','longitude\_std','height\_std'}, ...
      varargin{:} );
