function pscopexgnssv(varargin);
% pscopexgnssv( [...] );
% GNSS Velocity
h = timeplot({'velocity_forward','velocity_down'}, ...
      'GNSS Velocity', ...
      'Velocity', ...
      {'velocity\_forward','velocity\_down'}, ...
      varargin{:} );
