function pscopexahkt(varargin);
% pscopexahkt( [...] );
% Asc HK Temp
h = timeplot({'AscMtrT','AscMtrCtrlT','AscOutputPulleyT','AscConvT'}, ...
      'Asc HK Temp', ...
      'Temp', ...
      {'AscMtrT','AscMtrCtrlT','AscOutputPulleyT','AscConvT'}, ...
      varargin{:} );
