function pscopexgnssattitude(varargin);
% pscopexgnssattitude( [...] );
% GNSS Attitude
h = timeplot({'roll','pitch'}, ...
      'GNSS Attitude', ...
      'Attitude', ...
      {'roll','pitch'}, ...
      varargin{:} );
