function pscopexpmclsstatus1(varargin);
% pscopexpmclsstatus1( [...] );
% PMC Left S Status 1
h = ne_dstat({
  'DrvReset', 'PMC_Left_Status1', 0; ...
	'DrvIntErr', 'PMC_Left_Status1', 1; ...
	'ShortCir', 'PMC_Left_Status1', 2; ...
	'CurOverShoot', 'PMC_Left_Status1', 3; ...
	'DrvUnderV', 'PMC_Left_Status1', 4; ...
	'DrvOverV', 'PMC_Left_Status1', 5; ...
	'DrvOverT', 'PMC_Left_Status1', 6 }, 'Status 1', varargin{:} );
