function pscopexmpmclsstatus1(varargin);
% pscopexmpmclsstatus1( [...] );
% PMC Left S Status 1
h = ne_dstat({
  'Left_DrvReset', 'PMC_Left_Status1', 0; ...
	'Left_DrvIntErr', 'PMC_Left_Status1', 1; ...
	'Left_ShortCir', 'PMC_Left_Status1', 2; ...
	'Left_CurOverShoot', 'PMC_Left_Status1', 3; ...
	'Left_DrvUnderV', 'PMC_Left_Status1', 4; ...
	'Left_DrvOverV', 'PMC_Left_Status1', 5; ...
	'Left_DrvOverT', 'PMC_Left_Status1', 6 }, 'Status 1', varargin{:} );
