function pscopexmpmcrgg(varargin);
% pscopexmpmcrgg( [...] );
% PMC Right G Gains
h = timeplot({'PMC_Right_VL_Kp','PMC_Right_VL_Ki','PMC_Right_VL_Kd','PMC_Right_TCL_Kp','PMC_Right_TCL_Ki'}, ...
      'PMC Right G Gains', ...
      'Gains', ...
      {'PMC\_Right\_VL\_Kp','PMC\_Right\_VL\_Ki','PMC\_Right\_VL\_Kd','PMC\_Right\_TCL\_Kp','PMC\_Right\_TCL\_Ki'}, ...
      varargin{:} );
