function pscopexbmbbmbvla(varargin);
% pscopexbmbbmbvla( [...] );
% B3MB 28V1 Load Amps
h = timeplot({'EngPort28_I','B3MB_28V1_Load2_I','EngStbd28_I','DataSys28_I'}, ...
      'B3MB 28V1 Load Amps', ...
      'Amps', ...
      {'L1I','L1I','L1I','L1I'}, ...
      varargin{:} );
