function pscopexmpmcrsstatus3(varargin);
% pscopexmpmcrsstatus3( [...] );
% PMC Right S Status 3
h = ne_dstat({
  'LogEntryMissed', 'PMC_Right_Status3', 0; ...
	'SWDisable', 'PMC_Right_Status3', 1; ...
	'UserDisable', 'PMC_Right_Status3', 2; ...
	'UserPosInh', 'PMC_Right_Status3', 3; ...
	'UserNegInh', 'PMC_Right_Status3', 4; ...
	'CurLimiting', 'PMC_Right_Status3', 5; ...
	'ContCurFoldback', 'PMC_Right_Status3', 6; ...
	'CurLoopSat', 'PMC_Right_Status3', 7; ...
	'UserUnderV', 'PMC_Right_Status3', 8; ...
	'UserOverV', 'PMC_Right_Status3', 9; ...
	'NonSinComm', 'PMC_Right_Status3', 10; ...
	'PhaseDetectActive', 'PMC_Right_Status3', 11; ...
	'MotionEngActive', 'PMC_Right_Status3', 12; ...
	'UserAuxDisable', 'PMC_Right_Status3', 13; ...
	'ShuntRegActive', 'PMC_Right_Status3', 14; ...
	'PhaseDetectDone', 'PMC_Right_Status3', 15 }, 'Status 3', varargin{:} );
