function pscopexmpmcrrpm(varargin);
% pscopexmpmcrrpm( [...] );
% PMC Right RPM
h = timeplot({'PMC_Right_RPM_SP','PMC_Right_RPM_Demand','PMC_Right_RPM'}, ...
      'PMC Right RPM', ...
      'RPM', ...
      {'PMC\_Right\_RPM\_SP','PMC\_Right\_RPM\_Demand','PMC\_Right\_RPM'}, ...
      varargin{:} );
