function pscopexmpmcrc(varargin);
% pscopexmpmcrc( [...] );
% PMC Right Current
h = timeplot({'PMC_Right_I_Demand','PMC_Right_I_Measured'}, ...
      'PMC Right Current', ...
      'Current', ...
      {'PMC\_Right\_I\_Demand','PMC\_Right\_I\_Measured'}, ...
      varargin{:} );
