function pscopexmgnssp(varargin);
% pscopexmgnssp( [...] );
% GNSS Position
h = timeplot({'north_m','east_m'}, ...
      'GNSS Position', ...
      'Position', ...
      {'north\_m','east\_m'}, ...
      varargin{:} );
