function pscopexgnssh(varargin);
% pscopexgnssh( [...] );
% GNSS Heading
h = timeplot({'Course','Track','heading'}, ...
      'GNSS Heading', ...
      'Heading', ...
      {'Course','Track','heading'}, ...
      varargin{:} );
