function pscopexmgnssaccel(varargin);
% pscopexmgnssaccel( [...] );
% GNSS Accel
h = timeplot({'body_accel_x','body_accel_y','body_accel_z','g_force'}, ...
      'GNSS Accel', ...
      'Accel', ...
      {'body\_accel\_x','body\_accel\_y','body\_accel\_z','g\_force'}, ...
      varargin{:} );
