function pscopexmahkci(varargin);
% pscopexmahkci( [...] );
% Asc HK Ctrl Inp
h = timeplot({'AscCtrlInp'}, ...
      'Asc HK Ctrl Inp', ...
      'Ctrl Inp', ...
      {'AscCtrlInp'}, ...
      varargin{:} );
