function pscopexpmclsstatus4(varargin);
% pscopexpmclsstatus4( [...] );
% PMC Left S Status 4
h = ne_dstat({
  'ZeroVel', 'PMC_Left_Status4', 0; ...
	'AtCommand', 'PMC_Left_Status4', 1; ...
	'VelFollErr', 'PMC_Left_Status4', 2; ...
	'PosTargVelLim', 'PMC_Left_Status4', 3; ...
	'NegTargVelLim', 'PMC_Left_Status4', 4; ...
	'CmdLimiterAct', 'PMC_Left_Status4', 5; ...
	'InHomPos', 'PMC_Left_Status4', 6; ...
	'PosFollErr', 'PMC_Left_Status4', 7; ...
	'MaxTargPosLim', 'PMC_Left_Status4', 8; ...
	'MinTargPosLim', 'PMC_Left_Status4', 9; ...
	'SetPosActive', 'PMC_Left_Status4', 10; ...
	'HomingActive', 'PMC_Left_Status4', 12; ...
	'SafeTrqOff', 'PMC_Left_Status4', 13; ...
	'HomingDone', 'PMC_Left_Status4', 14; ...
	'ZeroPos', 'PMC_Left_Status4', 15 }, 'Status 4', varargin{:} );
