function pscopexmpmcrsstatus1(varargin);
% pscopexmpmcrsstatus1( [...] );
% PMC Right S Status 1
h = ne_dstat({
  'Right_DrvReset', 'PMC_Right_Status1', 0; ...
	'Right_DrvIntErr', 'PMC_Right_Status1', 1; ...
	'Right_ShortCir', 'PMC_Right_Status1', 2; ...
	'Right_CurOverShoot', 'PMC_Right_Status1', 3; ...
	'Right_DrvUnderV', 'PMC_Right_Status1', 4; ...
	'Right_DrvOverV', 'PMC_Right_Status1', 5; ...
	'Right_DrvOverT', 'PMC_Right_Status1', 6 }, 'Status 1', varargin{:} );
