function pscopexpmclsstatus2(varargin);
% pscopexpmclsstatus2( [...] );
% PMC Left S Status 2
h = ne_dstat({
  'ParRestoreErr', 'PMC_Left_Status2', 0; ...
	'ParStoreErr', 'PMC_Left_Status2', 1; ...
	'InvHallState', 'PMC_Left_Status2', 2; ...
	'PhaseSyncErr', 'PMC_Left_Status2', 3; ...
	'MotorOverT', 'PMC_Left_Status2', 4; ...
	'PhaseDetFault', 'PMC_Left_Status2', 5; ...
	'FBSensorErr', 'PMC_Left_Status2', 6; ...
	'MotorOverSpeed', 'PMC_Left_Status2', 7; ...
	'MaxMeasuredPos', 'PMC_Left_Status2', 8; ...
	'MinMeasuredPos', 'PMC_Left_Status2', 9; ...
	'CommError', 'PMC_Left_Status2', 10; ...
	'PWMBrokenWire', 'PMC_Left_Status2', 11; ...
	'MotionEngErr', 'PMC_Left_Status2', 12; ...
	'MotionEngAbrt', 'PMC_Left_Status2', 13 }, 'Status 2', varargin{:} );
