function pscopexmgnssh(varargin);
% pscopexmgnssh( [...] );
% GNSS Heading
h = timeplot({'Track','heading','Nav_Course'}, ...
      'GNSS Heading', ...
      'Heading', ...
      {'Track','heading','Nav\_Course'}, ...
      varargin{:} );
