function pscopexpmcrss(varargin);
% pscopexpmcrss( [...] );
% PMC Right S Status 0
h = ne_dstat({
  'Bridge_En', 'PMC_Right_Status0', 0; ...
	'DynBrk_En', 'PMC_Right_Status0', 1; ...
	'Stop_En', 'PMC_Right_Status0', 2; ...
	'PosStop_En', 'PMC_Right_Status0', 3; ...
	'NegStop_En', 'PMC_Right_Status0', 4; ...
	'PosTrqInh_In', 'PMC_Right_Status0', 5; ...
	'NegTrqInh_En', 'PMC_Right_Status0', 6; ...
	'ExtBrk_En', 'PMC_Right_Status0', 7 }, 'Status 0', varargin{:} );
