function pscopexmahkn(varargin);
% pscopexmahkn( [...] );
% Asc HK Nreports
h = timeplot({'AscNreports'}, ...
      'Asc HK Nreports', ...
      'Nreports', ...
      {'AscNreports'}, ...
      varargin{:} );
