function pscopexmpmcrsstatus6(varargin);
% pscopexmpmcrsstatus6( [...] );
% PMC Right S Status 6
h = ne_dstat({
  'Right_AbsPosValid', 'PMC_Right_Status6', 0; ...
	'Right_PosStopActive', 'PMC_Right_Status6', 1; ...
	'Right_NegStopActive', 'PMC_Right_Status6', 2; ...
	'Right_ConfigSelect', 'PMC_Right_Status6', 4; ...
	'Right_BrakeCommand', 'PMC_Right_Status6', 5; ...
	'Right_DigOut1', 'PMC_Right_Status6', 6; ...
	'Right_DigOut2', 'PMC_Right_Status6', 7 }, 'Status 6', varargin{:} );
