function pscopexpmcla(varargin);
% pscopexpmcla( [...] );
% PMC Left Accel
h = timeplot({'PMC_Left_MaxAccel','PMC_Left_MaxDecel'}, ...
      'PMC Left Accel', ...
      'Accel', ...
      {'PMC\_Left\_MaxAccel','PMC\_Left\_MaxDecel'}, ...
      varargin{:} );
