function dfs_out = rt_scopex(dfs)
% dfs = rt_scopex()
%   Create a data_fields object and setup all the buttons for realtime
%   plots
% dfs_out = rt_scopex(dfs)
%   Use the data_fields object and setup all the buttons for realtime plots
if nargin < 1
  dfs = data_fields('title', 'SCoPEx Platform', ...
    'Color', [.8 .8 1], ...
    'h_leading', 8, 'v_leading', 2, ...
    'btn_fontsize', 12, ...
    'txt_fontsize', 12);
  context_level = dfs.rt_init;
else
  context_level = 1;
end
dfs.start_tab('Main');
dfs.start_col;
dfs.plot('ms', 'label', 'System', 'plots', {'mssws'});
dfs.plot('mssws','label','SW Stat','vars',{'SWStat'});
dfs.plot('mtm', 'label', 'T Mbase', 'plots', {'mtmtd','mtmcpu','mtmram','mtmd'});
dfs.plot('mtmtd','label','T Drift','vars',{'SysTDrift'});
dfs.plot('mtmcpu','label','CPU','vars',{'CPU_Pct'});
dfs.plot('mtmram','label','RAM','vars',{'memused'});
dfs.plot('mtmd','label','Disk','vars',{'Disk'});
dfs.end_col;
dfs.start_col;
dfs.plot('mgnss', 'label', 'GNSS', 'plots', {'mgnsss','mgnssf','mgnssd','mgnssp','mgnssv','mgnssh','mgnssa','mgnssattitude','mgnssav','mgnssstd','mgnssstale'});
dfs.plot('mgnsss','label','System','vars',{'system_status'});
dfs.plot('mgnssf','label','Filters','vars',{{'name','orient_init','var_name','filter_status','bit_number',0},{'name','nav_init','var_name','filter_status','bit_number',1},{'name','heading_init','var_name','filter_status','bit_number',2},{'name','UTC_init','var_name','filter_status','bit_number',3},{'name','Int_GNSS_en','var_name','filter_status','bit_number',9},{'name','dual_heading_active','var_name','filter_status','bit_number',10},{'name','atm_alt_en','var_name','filter_status','bit_number',12}});
dfs.plot('mgnssd','label','Drift','vars',{'nav_drift'});
dfs.plot('mgnssp','label','Position','vars',{'latitude','longitude','height'});
dfs.plot('mgnssv','label','Velocity','vars',{'velocity_north','velocity_east','velocity_forward','velocity_down'});
dfs.plot('mgnssh','label','Heading','vars',{'Track','heading'});
dfs.plot('mgnssa','label','Accel','vars',{'body_accel_x','body_accel_y','body_accel_z','g_force'});
dfs.plot('mgnssattitude','label','Attitude','vars',{'roll','pitch'});
dfs.plot('mgnssav','label','Ang Vel','vars',{'angular_velocity_x','angular_velocity_y','angular_velocity_z'});
dfs.plot('mgnssstd','label','Std','vars',{'latitude_std','longitude_std','height_std'});
dfs.plot('mgnssstale','label','Stale','vars',{'SD_stale','SD_n_reports','SD_nc'});
dfs.end_col;
dfs.start_col;
dfs.plot('ma', 'label', 'Ascender', 'plots', {'map','mas','mac','mal'});
dfs.plot('map','label','Pos','vars',{'AscPosition'});
dfs.plot('mas','label','Speed','vars',{'AscSpeed'});
dfs.plot('mac','label','Cmd','vars',{'AscSpeedCmd'});
dfs.plot('mal','label','Limits','vars',{{'name','AscLimit1','var_name','AscStatus','bit_number',4},{'name','AscLimit2','var_name','AscStatus','bit_number',4}});
dfs.end_col;
dfs.start_col;
dfs.plot('mahk', 'label', 'Asc HK', 'plots', {'mahkv','mahki','mahkci','mahkm','mahkt','mahkn','mahks'});
dfs.plot('mahkv','label','V','vars',{'AscHoistV'});
dfs.plot('mahki','label','I','vars',{'AscHoistI'});
dfs.plot('mahkci','label','Ctrl Inp','vars',{'AscCtrlInp'});
dfs.plot('mahkm','label','Mode','vars',{'AscMode'});
dfs.plot('mahkt','label','Temp','vars',{'AscMtrT','AscMtrCtrlT','AscOutputPulleyT','AscConvT'});
dfs.plot('mahkn','label','Nreports','vars',{'AscNreports'});
dfs.plot('mahks','label','Stale','vars',{'AscStale'});
dfs.end_tab;
dfs.start_tab('Motors');
dfs.start_col;
dfs.plot('mpmc', 'label', 'PMC', 'plots', {'mpmcs'});
dfs.plot('mpmcs','label','Stale','vars',{'PMC_Stale','PMC_StaleF'});
dfs.plot('mpmcl', 'label', 'PMC Left', 'plots', {'mpmclrpm','mpmclc','mpmclv','mpmclp'});
dfs.plot('mpmclrpm','label','RPM','vars',{'PMC_Left_RPM_SP','PMC_Left_RPM_Demand','PMC_Left_RPM'});
dfs.plot('mpmclc','label','Current','vars',{'PMC_Left_I_Demand','PMC_Left_I_Measured'});
dfs.plot('mpmclv','label','Voltage','vars',{'PMC_Left_BusV'});
dfs.plot('mpmclp','label','Position','vars',{'PMC_Left_Pos_SP','PMC_Left_Pos_Demand','PMC_Left_Pos_Target','PMC_Left_Pos_Measured'});
dfs.end_col;
dfs.start_col;
dfs.plot('mpmcls', 'label', 'PMC Left S', 'plots', {'mpmclss','mpmclsstatus1','mpmclsstatus2','mpmclsstatus3','mpmclsstatus4','mpmclsstatus5','mpmclsstatus6'});
dfs.plot('mpmclss','label','Status 0','vars',{{'name','Bridge_En','var_name','PMC_Left_Status0','bit_number',0},{'name','DynBrk_En','var_name','PMC_Left_Status0','bit_number',1},{'name','Stop_En','var_name','PMC_Left_Status0','bit_number',2},{'name','PosStop_En','var_name','PMC_Left_Status0','bit_number',3},{'name','NegStop_En','var_name','PMC_Left_Status0','bit_number',4},{'name','PosTrqInh_In','var_name','PMC_Left_Status0','bit_number',5},{'name','NegTrqInh_En','var_name','PMC_Left_Status0','bit_number',6},{'name','ExtBrk_En','var_name','PMC_Left_Status0','bit_number',7}});
dfs.plot('mpmclsstatus1','label','Status 1','vars',{{'name','DrvReset','var_name','PMC_Left_Status1','bit_number',0},{'name','DrvIntErr','var_name','PMC_Left_Status1','bit_number',1},{'name','ShortCir','var_name','PMC_Left_Status1','bit_number',2},{'name','CurOverShoot','var_name','PMC_Left_Status1','bit_number',3},{'name','DrvUnderV','var_name','PMC_Left_Status1','bit_number',4},{'name','DrvOverV','var_name','PMC_Left_Status1','bit_number',5},{'name','DrvOverT','var_name','PMC_Left_Status1','bit_number',6}});
dfs.plot('mpmclsstatus2','label','Status 2','vars',{{'name','ParRestoreErr','var_name','PMC_Left_Status2','bit_number',0},{'name','ParStoreErr','var_name','PMC_Left_Status2','bit_number',1},{'name','InvHallState','var_name','PMC_Left_Status2','bit_number',2},{'name','PhaseSyncErr','var_name','PMC_Left_Status2','bit_number',3},{'name','MotorOverT','var_name','PMC_Left_Status2','bit_number',4},{'name','PhaseDetFault','var_name','PMC_Left_Status2','bit_number',5},{'name','FBSensorErr','var_name','PMC_Left_Status2','bit_number',6},{'name','MotorOverSpeed','var_name','PMC_Left_Status2','bit_number',7},{'name','MaxMeasuredPos','var_name','PMC_Left_Status2','bit_number',8},{'name','MinMeasuredPos','var_name','PMC_Left_Status2','bit_number',9},{'name','CommError','var_name','PMC_Left_Status2','bit_number',10},{'name','PWMBrokenWire','var_name','PMC_Left_Status2','bit_number',11},{'name','MotionEngErr','var_name','PMC_Left_Status2','bit_number',12},{'name','MotionEngAbrt','var_name','PMC_Left_Status2','bit_number',13}});
dfs.plot('mpmclsstatus3','label','Status 3','vars',{{'name','LogEntryMissed','var_name','PMC_Left_Status3','bit_number',0},{'name','SWDisable','var_name','PMC_Left_Status3','bit_number',1},{'name','UserDisable','var_name','PMC_Left_Status3','bit_number',2},{'name','UserPosInh','var_name','PMC_Left_Status3','bit_number',3},{'name','UserNegInh','var_name','PMC_Left_Status3','bit_number',4},{'name','CurLimiting','var_name','PMC_Left_Status3','bit_number',5},{'name','ContCurFoldback','var_name','PMC_Left_Status3','bit_number',6},{'name','CurLoopSat','var_name','PMC_Left_Status3','bit_number',7},{'name','UserUnderV','var_name','PMC_Left_Status3','bit_number',8},{'name','UserOverV','var_name','PMC_Left_Status3','bit_number',9},{'name','NonSinComm','var_name','PMC_Left_Status3','bit_number',10},{'name','PhaseDetectActive','var_name','PMC_Left_Status3','bit_number',11},{'name','MotionEngActive','var_name','PMC_Left_Status3','bit_number',12},{'name','UserAuxDisable','var_name','PMC_Left_Status3','bit_number',13},{'name','ShuntRegActive','var_name','PMC_Left_Status3','bit_number',14},{'name','PhaseDetectDone','var_name','PMC_Left_Status3','bit_number',15}});
dfs.plot('mpmclsstatus4','label','Status 4','vars',{{'name','ZeroVel','var_name','PMC_Left_Status4','bit_number',0},{'name','AtCommand','var_name','PMC_Left_Status4','bit_number',1},{'name','VelFollErr','var_name','PMC_Left_Status4','bit_number',2},{'name','PosTargVelLim','var_name','PMC_Left_Status4','bit_number',3},{'name','NegTargVelLim','var_name','PMC_Left_Status4','bit_number',4},{'name','CmdLimiterAct','var_name','PMC_Left_Status4','bit_number',5},{'name','InHomPos','var_name','PMC_Left_Status4','bit_number',6},{'name','PosFollErr','var_name','PMC_Left_Status4','bit_number',7},{'name','MaxTargPosLim','var_name','PMC_Left_Status4','bit_number',8},{'name','MinTargPosLim','var_name','PMC_Left_Status4','bit_number',9},{'name','SetPosActive','var_name','PMC_Left_Status4','bit_number',10},{'name','HomingActive','var_name','PMC_Left_Status4','bit_number',12},{'name','SafeTrqOff','var_name','PMC_Left_Status4','bit_number',13},{'name','HomingDone','var_name','PMC_Left_Status4','bit_number',14},{'name','ZeroPos','var_name','PMC_Left_Status4','bit_number',15}});
dfs.plot('mpmclsstatus5','label','Status 5','vars',{{'name','CmddStop','var_name','PMC_Left_Status5','bit_number',6},{'name','UserStop','var_name','PMC_Left_Status5','bit_number',7},{'name','Cap1Active','var_name','PMC_Left_Status5','bit_number',8},{'name','Cap2Active','var_name','PMC_Left_Status5','bit_number',9},{'name','Cap3Active','var_name','PMC_Left_Status5','bit_number',10},{'name','CmddPosLim','var_name','PMC_Left_Status5','bit_number',11},{'name','CmddNegLim','var_name','PMC_Left_Status5','bit_number',12}});
dfs.plot('mpmclsstatus6','label','Status 6','vars',{{'name','AbsPosValid','var_name','PMC_Left_Status6','bit_number',0},{'name','PosStopActive','var_name','PMC_Left_Status6','bit_number',1},{'name','NegStopActive','var_name','PMC_Left_Status6','bit_number',2},{'name','ConfigSelect','var_name','PMC_Left_Status6','bit_number',4},{'name','BrakeCommand','var_name','PMC_Left_Status6','bit_number',5},{'name','DigOut1','var_name','PMC_Left_Status6','bit_number',6},{'name','DigOut2','var_name','PMC_Left_Status6','bit_number',7}});
dfs.plot('mpmclg', 'label', 'PMC Left G', 'plots', {'mpmclgg'});
dfs.plot('mpmclgg','label','Gains','vars',{'PMC_Left_VL_Kp','PMC_Left_VL_Ki','PMC_Left_VL_Kd','PMC_Left_TCL_Kp','PMC_Left_TCL_Ki'});
dfs.end_col;
dfs.start_col;
dfs.plot('mpmcr', 'label', 'PMC Right', 'plots', {'mpmcrrpm','mpmcrc','mpmcrv','mpmcrp'});
dfs.plot('mpmcrrpm','label','RPM','vars',{'PMC_Right_RPM_SP','PMC_Right_RPM_Demand','PMC_Right_RPM'});
dfs.plot('mpmcrc','label','Current','vars',{'PMC_Right_I_Demand','PMC_Right_I_Measured'});
dfs.plot('mpmcrv','label','Voltage','vars',{'PMC_Right_BusV'});
dfs.plot('mpmcrp','label','Position','vars',{'PMC_Right_Pos_SP','PMC_Right_Pos_Demand','PMC_Right_Pos_Target','PMC_Right_Pos_Measured'});
dfs.end_col;
dfs.start_col;
dfs.plot('mpmcrs', 'label', 'PMC Right S', 'plots', {'mpmcrss','mpmcrsstatus1','mpmcrsstatus2','mpmcrsstatus3','mpmcrsstatus4','mpmcrsstatus5','mpmcrsstatus6'});
dfs.plot('mpmcrss','label','Status 0','vars',{{'name','Bridge_En','var_name','PMC_Right_Status0','bit_number',0},{'name','DynBrk_En','var_name','PMC_Right_Status0','bit_number',1},{'name','Stop_En','var_name','PMC_Right_Status0','bit_number',2},{'name','PosStop_En','var_name','PMC_Right_Status0','bit_number',3},{'name','NegStop_En','var_name','PMC_Right_Status0','bit_number',4},{'name','PosTrqInh_In','var_name','PMC_Right_Status0','bit_number',5},{'name','NegTrqInh_En','var_name','PMC_Right_Status0','bit_number',6},{'name','ExtBrk_En','var_name','PMC_Right_Status0','bit_number',7}});
dfs.plot('mpmcrsstatus1','label','Status 1','vars',{{'name','DrvReset','var_name','PMC_Right_Status1','bit_number',0},{'name','DrvIntErr','var_name','PMC_Right_Status1','bit_number',1},{'name','ShortCir','var_name','PMC_Right_Status1','bit_number',2},{'name','CurOverShoot','var_name','PMC_Right_Status1','bit_number',3},{'name','DrvUnderV','var_name','PMC_Right_Status1','bit_number',4},{'name','DrvOverV','var_name','PMC_Right_Status1','bit_number',5},{'name','DrvOverT','var_name','PMC_Right_Status1','bit_number',6}});
dfs.plot('mpmcrsstatus2','label','Status 2','vars',{{'name','ParRestoreErr','var_name','PMC_Right_Status2','bit_number',0},{'name','ParStoreErr','var_name','PMC_Right_Status2','bit_number',1},{'name','InvHallState','var_name','PMC_Right_Status2','bit_number',2},{'name','PhaseSyncErr','var_name','PMC_Right_Status2','bit_number',3},{'name','MotorOverT','var_name','PMC_Right_Status2','bit_number',4},{'name','PhaseDetFault','var_name','PMC_Right_Status2','bit_number',5},{'name','FBSensorErr','var_name','PMC_Right_Status2','bit_number',6},{'name','MotorOverSpeed','var_name','PMC_Right_Status2','bit_number',7},{'name','MaxMeasuredPos','var_name','PMC_Right_Status2','bit_number',8},{'name','MinMeasuredPos','var_name','PMC_Right_Status2','bit_number',9},{'name','CommError','var_name','PMC_Right_Status2','bit_number',10},{'name','PWMBrokenWire','var_name','PMC_Right_Status2','bit_number',11},{'name','MotionEngErr','var_name','PMC_Right_Status2','bit_number',12},{'name','MotionEngAbrt','var_name','PMC_Right_Status2','bit_number',13}});
dfs.plot('mpmcrsstatus3','label','Status 3','vars',{{'name','LogEntryMissed','var_name','PMC_Right_Status3','bit_number',0},{'name','SWDisable','var_name','PMC_Right_Status3','bit_number',1},{'name','UserDisable','var_name','PMC_Right_Status3','bit_number',2},{'name','UserPosInh','var_name','PMC_Right_Status3','bit_number',3},{'name','UserNegInh','var_name','PMC_Right_Status3','bit_number',4},{'name','CurLimiting','var_name','PMC_Right_Status3','bit_number',5},{'name','ContCurFoldback','var_name','PMC_Right_Status3','bit_number',6},{'name','CurLoopSat','var_name','PMC_Right_Status3','bit_number',7},{'name','UserUnderV','var_name','PMC_Right_Status3','bit_number',8},{'name','UserOverV','var_name','PMC_Right_Status3','bit_number',9},{'name','NonSinComm','var_name','PMC_Right_Status3','bit_number',10},{'name','PhaseDetectActive','var_name','PMC_Right_Status3','bit_number',11},{'name','MotionEngActive','var_name','PMC_Right_Status3','bit_number',12},{'name','UserAuxDisable','var_name','PMC_Right_Status3','bit_number',13},{'name','ShuntRegActive','var_name','PMC_Right_Status3','bit_number',14},{'name','PhaseDetectDone','var_name','PMC_Right_Status3','bit_number',15}});
dfs.plot('mpmcrsstatus4','label','Status 4','vars',{{'name','ZeroVel','var_name','PMC_Right_Status4','bit_number',0},{'name','AtCommand','var_name','PMC_Right_Status4','bit_number',1},{'name','VelFollErr','var_name','PMC_Right_Status4','bit_number',2},{'name','PosTargVelLim','var_name','PMC_Right_Status4','bit_number',3},{'name','NegTargVelLim','var_name','PMC_Right_Status4','bit_number',4},{'name','CmdLimiterAct','var_name','PMC_Right_Status4','bit_number',5},{'name','InHomPos','var_name','PMC_Right_Status4','bit_number',6},{'name','PosFollErr','var_name','PMC_Right_Status4','bit_number',7},{'name','MaxTargPosLim','var_name','PMC_Right_Status4','bit_number',8},{'name','MinTargPosLim','var_name','PMC_Right_Status4','bit_number',9},{'name','SetPosActive','var_name','PMC_Right_Status4','bit_number',10},{'name','HomingActive','var_name','PMC_Right_Status4','bit_number',12},{'name','SafeTrqOff','var_name','PMC_Right_Status4','bit_number',13},{'name','HomingDone','var_name','PMC_Right_Status4','bit_number',14},{'name','ZeroPos','var_name','PMC_Right_Status4','bit_number',15}});
dfs.plot('mpmcrsstatus5','label','Status 5','vars',{{'name','CmddStop','var_name','PMC_Right_Status5','bit_number',6},{'name','UserStop','var_name','PMC_Right_Status5','bit_number',7},{'name','Cap1Active','var_name','PMC_Right_Status5','bit_number',8},{'name','Cap2Active','var_name','PMC_Right_Status5','bit_number',9},{'name','Cap3Active','var_name','PMC_Right_Status5','bit_number',10},{'name','CmddPosLim','var_name','PMC_Right_Status5','bit_number',11},{'name','CmddNegLim','var_name','PMC_Right_Status5','bit_number',12}});
dfs.plot('mpmcrsstatus6','label','Status 6','vars',{{'name','AbsPosValid','var_name','PMC_Right_Status6','bit_number',0},{'name','PosStopActive','var_name','PMC_Right_Status6','bit_number',1},{'name','NegStopActive','var_name','PMC_Right_Status6','bit_number',2},{'name','ConfigSelect','var_name','PMC_Right_Status6','bit_number',4},{'name','BrakeCommand','var_name','PMC_Right_Status6','bit_number',5},{'name','DigOut1','var_name','PMC_Right_Status6','bit_number',6},{'name','DigOut2','var_name','PMC_Right_Status6','bit_number',7}});
dfs.plot('mpmcrg', 'label', 'PMC Right G', 'plots', {'mpmcrgg'});
dfs.plot('mpmcrgg','label','Gains','vars',{'PMC_Right_VL_Kp','PMC_Right_VL_Ki','PMC_Right_VL_Kd','PMC_Right_TCL_Kp','PMC_Right_TCL_Ki'});
dfs.end_tab;
dfs.start_tab('B3MB');
dfs.start_col;
dfs.plot('bmbbmbvb', 'label', 'B3MB 28V1 Batt', 'plots', {'bmbbmbvbv','bmbbmbvba','bmbbmbvbt','bmbbmbvbs','bmbbmbvbf'});
dfs.plot('bmbbmbvbv','label','Volts','vars',{'B3MB_28V1_Batt1_V','B3MB_28V1_Batt2_V','B3MB_28V1_Batt3_V','B3MB_28V1_Batt4_V','B3MB_28V1_Bus_V'});
dfs.plot('bmbbmbvba','label','Amps','vars',{'B3MB_28V1_Batt1_I','B3MB_28V1_Batt2_I','B3MB_28V1_Batt3_I','B3MB_28V1_Batt4_I'});
dfs.plot('bmbbmbvbt','label','Temp','vars',{'B3MB_28V1_T1','B3MB_28V1_T2','B3MB_28V1_T3','B3MB_28V1_T4','B3MB_28V1_T5'});
dfs.plot('bmbbmbvbs','label','Status','vars',{{'name','B1S','var_name','B3MB_28V1_Cmd_S','bit_number',0},{'name','B2S','var_name','B3MB_28V1_Cmd_S','bit_number',1},{'name','B3S','var_name','B3MB_28V1_Cmd_S','bit_number',2},{'name','B4S','var_name','B3MB_28V1_Cmd_S','bit_number',3},{'name','Stat_LED','var_name','B3MB_28V1_LED_S','bit_number',0},{'name','Fault_LED','var_name','B3MB_28V1_LED_S','bit_number',0},{'name','ID_CPU','var_name','B3MB_28V1_LED_S','bit_number',0}});
dfs.plot('bmbbmbvbf','label','Fault','vars',{{'name','B1F','var_name','B3MB_28V1_Cmd_S','bit_number',8},{'name','B2F','var_name','B3MB_28V1_Cmd_S','bit_number',9},{'name','B3F','var_name','B3MB_28V1_Cmd_S','bit_number',10},{'name','B4F','var_name','B3MB_28V1_Cmd_S','bit_number',11}});
dfs.plot('bmbbmbvl', 'label', 'B3MB 28V1 Load', 'plots', {'bmbbmbvlv','bmbbmbvla','bmbbmbvls','bmbbmbvlf'});
dfs.plot('bmbbmbvlv','label','Volts','vars',{'B3MB_28V1_Load1_V','B3MB_28V1_Load2_V','B3MB_28V1_Load3_V','B3MB_28V1_Load4_V'});
dfs.plot('bmbbmbvla','label','Amps','vars',{'B3MB_28V1_Load1_I','B3MB_28V1_Load2_I','B3MB_28V1_Load3_I','B3MB_28V1_Load4_I'});
dfs.plot('bmbbmbvls','label','Status','vars',{{'name','L1S','var_name','B3MB_28V1_Cmd_S','bit_number',4},{'name','L2S','var_name','B3MB_28V1_Cmd_S','bit_number',5},{'name','L3S','var_name','B3MB_28V1_Cmd_S','bit_number',6},{'name','L4S','var_name','B3MB_28V1_Cmd_S','bit_number',7}});
dfs.plot('bmbbmbvlf','label','Fault','vars',{{'name','L1F','var_name','B3MB_28V1_Cmd_S','bit_number',12},{'name','L2F','var_name','B3MB_28V1_Cmd_S','bit_number',13},{'name','L3F','var_name','B3MB_28V1_Cmd_S','bit_number',14},{'name','L4F','var_name','B3MB_28V1_Cmd_S','bit_number',15}});
dfs.end_col;
dfs.start_col;
dfs.plot('b3mb_b3mb_100v1_batt', 'label', 'B3MB 100V1 Batt', 'plots', {'b3mb_b3mb_100v1_battv','b3mb_b3mb_100v1_batta','b3mb_b3mb_100v1_battt','b3mb_b3mb_100v1_batts','b3mb_b3mb_100v1_battf'});
dfs.plot('b3mb_b3mb_100v1_battv','label','Volts','vars',{'B3MB_100V1_Batt1_V','B3MB_100V1_Batt2_V','B3MB_100V1_Batt3_V','B3MB_100V1_Batt4_V','B3MB_100V1_Bus_V'});
dfs.plot('b3mb_b3mb_100v1_batta','label','Amps','vars',{'B3MB_100V1_Batt1_I','B3MB_100V1_Batt2_I','B3MB_100V1_Batt3_I','B3MB_100V1_Batt4_I'});
dfs.plot('b3mb_b3mb_100v1_battt','label','Temp','vars',{'B3MB_100V1_T1','B3MB_100V1_T2','B3MB_100V1_T3','B3MB_100V1_T4','B3MB_100V1_T5'});
dfs.plot('b3mb_b3mb_100v1_batts','label','Status','vars',{{'name','B1S','var_name','B3MB_100V1_Cmd_S','bit_number',0},{'name','B2S','var_name','B3MB_100V1_Cmd_S','bit_number',1},{'name','B3S','var_name','B3MB_100V1_Cmd_S','bit_number',2},{'name','B4S','var_name','B3MB_100V1_Cmd_S','bit_number',3},{'name','Stat_LED','var_name','B3MB_100V1_LED_S','bit_number',0},{'name','Fault_LED','var_name','B3MB_100V1_LED_S','bit_number',0},{'name','ID_CPU','var_name','B3MB_100V1_LED_S','bit_number',0}});
dfs.plot('b3mb_b3mb_100v1_battf','label','Fault','vars',{{'name','B1F','var_name','B3MB_100V1_Cmd_S','bit_number',8},{'name','B2F','var_name','B3MB_100V1_Cmd_S','bit_number',9},{'name','B3F','var_name','B3MB_100V1_Cmd_S','bit_number',10},{'name','B4F','var_name','B3MB_100V1_Cmd_S','bit_number',11}});
dfs.plot('b3mb_b3mb_100v1_load', 'label', 'B3MB 100V1 Load', 'plots', {'b3mb_b3mb_100v1_loadv','b3mb_b3mb_100v1_loada','b3mb_b3mb_100v1_loads','b3mb_b3mb_100v1_loadf'});
dfs.plot('b3mb_b3mb_100v1_loadv','label','Volts','vars',{'B3MB_100V1_Load1_V','B3MB_100V1_Load2_V','B3MB_100V1_Load3_V','B3MB_100V1_Load4_V'});
dfs.plot('b3mb_b3mb_100v1_loada','label','Amps','vars',{'B3MB_100V1_Load1_I','B3MB_100V1_Load2_I','B3MB_100V1_Load3_I','B3MB_100V1_Load4_I'});
dfs.plot('b3mb_b3mb_100v1_loads','label','Status','vars',{{'name','L1S','var_name','B3MB_100V1_Cmd_S','bit_number',4},{'name','L2S','var_name','B3MB_100V1_Cmd_S','bit_number',5},{'name','L3S','var_name','B3MB_100V1_Cmd_S','bit_number',6},{'name','L4S','var_name','B3MB_100V1_Cmd_S','bit_number',7}});
dfs.plot('b3mb_b3mb_100v1_loadf','label','Fault','vars',{{'name','L1F','var_name','B3MB_100V1_Cmd_S','bit_number',12},{'name','L2F','var_name','B3MB_100V1_Cmd_S','bit_number',13},{'name','L3F','var_name','B3MB_100V1_Cmd_S','bit_number',14},{'name','L4F','var_name','B3MB_100V1_Cmd_S','bit_number',15}});
dfs.end_col;
dfs.start_col;
dfs.plot('b3mb_b3mb_100v2_batt', 'label', 'B3MB 100V2 Batt', 'plots', {'b3mb_b3mb_100v2_battv','b3mb_b3mb_100v2_batta','b3mb_b3mb_100v2_battt','b3mb_b3mb_100v2_batts','b3mb_b3mb_100v2_battf'});
dfs.plot('b3mb_b3mb_100v2_battv','label','Volts','vars',{'B3MB_100V2_Batt1_V','B3MB_100V2_Batt2_V','B3MB_100V2_Batt3_V','B3MB_100V2_Batt4_V','B3MB_100V2_Bus_V'});
dfs.plot('b3mb_b3mb_100v2_batta','label','Amps','vars',{'B3MB_100V2_Batt1_I','B3MB_100V2_Batt2_I','B3MB_100V2_Batt3_I','B3MB_100V2_Batt4_I'});
dfs.plot('b3mb_b3mb_100v2_battt','label','Temp','vars',{'B3MB_100V2_T1','B3MB_100V2_T2','B3MB_100V2_T3','B3MB_100V2_T4','B3MB_100V2_T5'});
dfs.plot('b3mb_b3mb_100v2_batts','label','Status','vars',{{'name','B1S','var_name','B3MB_100V2_Cmd_S','bit_number',0},{'name','B2S','var_name','B3MB_100V2_Cmd_S','bit_number',1},{'name','B3S','var_name','B3MB_100V2_Cmd_S','bit_number',2},{'name','B4S','var_name','B3MB_100V2_Cmd_S','bit_number',3},{'name','Stat_LED','var_name','B3MB_100V2_LED_S','bit_number',0},{'name','Fault_LED','var_name','B3MB_100V2_LED_S','bit_number',0},{'name','ID_CPU','var_name','B3MB_100V2_LED_S','bit_number',0}});
dfs.plot('b3mb_b3mb_100v2_battf','label','Fault','vars',{{'name','B1F','var_name','B3MB_100V2_Cmd_S','bit_number',8},{'name','B2F','var_name','B3MB_100V2_Cmd_S','bit_number',9},{'name','B3F','var_name','B3MB_100V2_Cmd_S','bit_number',10},{'name','B4F','var_name','B3MB_100V2_Cmd_S','bit_number',11}});
dfs.plot('b3mb_b3mb_100v2_load', 'label', 'B3MB 100V2 Load', 'plots', {'b3mb_b3mb_100v2_loadv','b3mb_b3mb_100v2_loada','b3mb_b3mb_100v2_loads','b3mb_b3mb_100v2_loadf'});
dfs.plot('b3mb_b3mb_100v2_loadv','label','Volts','vars',{'B3MB_100V2_Load1_V','B3MB_100V2_Load2_V','B3MB_100V2_Load3_V','B3MB_100V2_Load4_V'});
dfs.plot('b3mb_b3mb_100v2_loada','label','Amps','vars',{'B3MB_100V2_Load1_I','B3MB_100V2_Load2_I','B3MB_100V2_Load3_I','B3MB_100V2_Load4_I'});
dfs.plot('b3mb_b3mb_100v2_loads','label','Status','vars',{{'name','L1S','var_name','B3MB_100V2_Cmd_S','bit_number',4},{'name','L2S','var_name','B3MB_100V2_Cmd_S','bit_number',5},{'name','L3S','var_name','B3MB_100V2_Cmd_S','bit_number',6},{'name','L4S','var_name','B3MB_100V2_Cmd_S','bit_number',7}});
dfs.plot('b3mb_b3mb_100v2_loadf','label','Fault','vars',{{'name','L1F','var_name','B3MB_100V2_Cmd_S','bit_number',12},{'name','L2F','var_name','B3MB_100V2_Cmd_S','bit_number',13},{'name','L3F','var_name','B3MB_100V2_Cmd_S','bit_number',14},{'name','L4F','var_name','B3MB_100V2_Cmd_S','bit_number',15}});
dfs.end_col;
dfs.start_col;
dfs.plot('b3mb_b3mb_100v3_batt', 'label', 'B3MB 100V3 Batt', 'plots', {'b3mb_b3mb_100v3_battv','b3mb_b3mb_100v3_batta','b3mb_b3mb_100v3_battt','b3mb_b3mb_100v3_batts','b3mb_b3mb_100v3_battf'});
dfs.plot('b3mb_b3mb_100v3_battv','label','Volts','vars',{'B3MB_100V3_Batt1_V','B3MB_100V3_Batt2_V','B3MB_100V3_Batt3_V','B3MB_100V3_Batt4_V','B3MB_100V3_Bus_V'});
dfs.plot('b3mb_b3mb_100v3_batta','label','Amps','vars',{'B3MB_100V3_Batt1_I','B3MB_100V3_Batt2_I','B3MB_100V3_Batt3_I','B3MB_100V3_Batt4_I'});
dfs.plot('b3mb_b3mb_100v3_battt','label','Temp','vars',{'B3MB_100V3_T1','B3MB_100V3_T2','B3MB_100V3_T3','B3MB_100V3_T4','B3MB_100V3_T5'});
dfs.plot('b3mb_b3mb_100v3_batts','label','Status','vars',{{'name','B1S','var_name','B3MB_100V3_Cmd_S','bit_number',0},{'name','B2S','var_name','B3MB_100V3_Cmd_S','bit_number',1},{'name','B3S','var_name','B3MB_100V3_Cmd_S','bit_number',2},{'name','B4S','var_name','B3MB_100V3_Cmd_S','bit_number',3},{'name','Stat_LED','var_name','B3MB_100V3_LED_S','bit_number',0},{'name','Fault_LED','var_name','B3MB_100V3_LED_S','bit_number',0},{'name','ID_CPU','var_name','B3MB_100V3_LED_S','bit_number',0}});
dfs.plot('b3mb_b3mb_100v3_battf','label','Fault','vars',{{'name','B1F','var_name','B3MB_100V3_Cmd_S','bit_number',8},{'name','B2F','var_name','B3MB_100V3_Cmd_S','bit_number',9},{'name','B3F','var_name','B3MB_100V3_Cmd_S','bit_number',10},{'name','B4F','var_name','B3MB_100V3_Cmd_S','bit_number',11}});
dfs.plot('b3mb_b3mb_100v3_load', 'label', 'B3MB 100V3 Load', 'plots', {'b3mb_b3mb_100v3_loadv','b3mb_b3mb_100v3_loada','b3mb_b3mb_100v3_loads','b3mb_b3mb_100v3_loadf'});
dfs.plot('b3mb_b3mb_100v3_loadv','label','Volts','vars',{'B3MB_100V3_Load1_V','B3MB_100V3_Load2_V','B3MB_100V3_Load3_V','B3MB_100V3_Load4_V'});
dfs.plot('b3mb_b3mb_100v3_loada','label','Amps','vars',{'B3MB_100V3_Load1_I','B3MB_100V3_Load2_I','B3MB_100V3_Load3_I','B3MB_100V3_Load4_I'});
dfs.plot('b3mb_b3mb_100v3_loads','label','Status','vars',{{'name','L1S','var_name','B3MB_100V3_Cmd_S','bit_number',4},{'name','L2S','var_name','B3MB_100V3_Cmd_S','bit_number',5},{'name','L3S','var_name','B3MB_100V3_Cmd_S','bit_number',6},{'name','L4S','var_name','B3MB_100V3_Cmd_S','bit_number',7}});
dfs.plot('b3mb_b3mb_100v3_loadf','label','Fault','vars',{{'name','L1F','var_name','B3MB_100V3_Cmd_S','bit_number',12},{'name','L2F','var_name','B3MB_100V3_Cmd_S','bit_number',13},{'name','L3F','var_name','B3MB_100V3_Cmd_S','bit_number',14},{'name','L4F','var_name','B3MB_100V3_Cmd_S','bit_number',15}});
dfs.end_col;
dfs.start_col;
dfs.plot('b3mb_b3mb_100v4_batt', 'label', 'B3MB 100V4 Batt', 'plots', {'b3mb_b3mb_100v4_battv','b3mb_b3mb_100v4_batta','b3mb_b3mb_100v4_battt','b3mb_b3mb_100v4_batts','b3mb_b3mb_100v4_battf'});
dfs.plot('b3mb_b3mb_100v4_battv','label','Volts','vars',{'B3MB_100V4_Batt1_V','B3MB_100V4_Batt2_V','B3MB_100V4_Batt3_V','B3MB_100V4_Batt4_V','B3MB_100V4_Bus_V'});
dfs.plot('b3mb_b3mb_100v4_batta','label','Amps','vars',{'B3MB_100V4_Batt1_I','B3MB_100V4_Batt2_I','B3MB_100V4_Batt3_I','B3MB_100V4_Batt4_I'});
dfs.plot('b3mb_b3mb_100v4_battt','label','Temp','vars',{'B3MB_100V4_T1','B3MB_100V4_T2','B3MB_100V4_T3','B3MB_100V4_T4','B3MB_100V4_T5'});
dfs.plot('b3mb_b3mb_100v4_batts','label','Status','vars',{{'name','B1S','var_name','B3MB_100V4_Cmd_S','bit_number',0},{'name','B2S','var_name','B3MB_100V4_Cmd_S','bit_number',1},{'name','B3S','var_name','B3MB_100V4_Cmd_S','bit_number',2},{'name','B4S','var_name','B3MB_100V4_Cmd_S','bit_number',3},{'name','Stat_LED','var_name','B3MB_100V4_LED_S','bit_number',0},{'name','Fault_LED','var_name','B3MB_100V4_LED_S','bit_number',0},{'name','ID_CPU','var_name','B3MB_100V4_LED_S','bit_number',0}});
dfs.plot('b3mb_b3mb_100v4_battf','label','Fault','vars',{{'name','B1F','var_name','B3MB_100V4_Cmd_S','bit_number',8},{'name','B2F','var_name','B3MB_100V4_Cmd_S','bit_number',9},{'name','B3F','var_name','B3MB_100V4_Cmd_S','bit_number',10},{'name','B4F','var_name','B3MB_100V4_Cmd_S','bit_number',11}});
dfs.plot('b3mb_b3mb_100v4_load', 'label', 'B3MB 100V4 Load', 'plots', {'b3mb_b3mb_100v4_loadv','b3mb_b3mb_100v4_loada','b3mb_b3mb_100v4_loads','b3mb_b3mb_100v4_loadf'});
dfs.plot('b3mb_b3mb_100v4_loadv','label','Volts','vars',{'B3MB_100V4_Load1_V','B3MB_100V4_Load2_V','B3MB_100V4_Load3_V','B3MB_100V4_Load4_V'});
dfs.plot('b3mb_b3mb_100v4_loada','label','Amps','vars',{'B3MB_100V4_Load1_I','B3MB_100V4_Load2_I','B3MB_100V4_Load3_I','B3MB_100V4_Load4_I'});
dfs.plot('b3mb_b3mb_100v4_loads','label','Status','vars',{{'name','L1S','var_name','B3MB_100V4_Cmd_S','bit_number',4},{'name','L2S','var_name','B3MB_100V4_Cmd_S','bit_number',5},{'name','L3S','var_name','B3MB_100V4_Cmd_S','bit_number',6},{'name','L4S','var_name','B3MB_100V4_Cmd_S','bit_number',7}});
dfs.plot('b3mb_b3mb_100v4_loadf','label','Fault','vars',{{'name','L1F','var_name','B3MB_100V4_Cmd_S','bit_number',12},{'name','L2F','var_name','B3MB_100V4_Cmd_S','bit_number',13},{'name','L3F','var_name','B3MB_100V4_Cmd_S','bit_number',14},{'name','L4F','var_name','B3MB_100V4_Cmd_S','bit_number',15}});
dfs.end_tab;
dfs.end_col;
dfs.resize(context_level);
dfs.set_connection('127.0.0.1', 1080);
if nargout > 0
  dfs_out = dfs;
end
